#H2 DB
#spring.application.name=JobService
#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:mem:test

#Postgres config
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=Test
spring.datasource.password=Test
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Actuator config
management.endpoints.web.exposure.include=*
#/health endpoint customization
management.endpoint.health.show-details=always
#/info endpoint customization
management.info.env.enabled=true
info.app.name=JobApplication
info.app.description=Job app build by CHS
info.app.version=1.0.0
